version: '3.8'

networks:
  web: {}

services:
  chrome:
    image: seleniarm/standalone-chromium
    environment:
      - SE_NODE_SESSION_TIMEOUT=172800
      - START_XVFB=false
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=5
    privileged: true
    shm_size: 2g
    restart: always
    networks:
      - web
    ports:
      - "4444:4444"
  bot:
    build: ./bot
    restart: always
    networks:
      - web
    volumes:
      - $SCREENSHOT_DIRECTORY:/usr/src/app/screenshots
      - $ACCOUNTS_JSON:/usr/src/app/accounts.json
    depends_on:
      - chrome
    environment:
      - IS_DOCKERIZED=1
      - OBSERVER_LOGIN=$OBSERVER_LOGIN
      - OBSERVER_PASSWORD=$OBSERVER_PASSWORD
      - PUBLISHER_LOGIN=$PUBLISHER_LOGIN
      - PUBLISHER_PASSWORD=$PUBLISHER_PASSWORD
      - SCREENSHOT_DIRECTORY=/usr/src/app/screenshots
      - ACCOUNTS_JSON=/usr/src/app/accounts.json
      - TELEGRAM_API_KEY=$TELEGRAM_API_KEY
      - TELEGRAM_CHANNEL_ID=$TELEGRAM_CHANNEL_ID